apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-domain-issuer
spec:
  acme:
    email: email-to-register-domain
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        cloudflare:
          email: cloudflare-email
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
